// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProduct struct {
	Name      string  `json:"name"`
	Price     float64 `json:"price"`
	Inventory int     `json:"inventory"`
}

type Product struct {
	ID        string  `json:"_id" bson:"_id"`
	Name      string  `json:"name"`
	Price     float64 `json:"price"`
	Inventory int     `json:"inventory"`
}
